### ISSUE TITLE
Data upload problem

### ISSUE THREAD

**Issue by OryLies** [shendurelab/MMCA#1]
Best,

I want to look at the Sox9 Knockout data, but when I try to load the data it fails.
I reformed the files from GEO to features.tsv.gz, barcodes.tsv.gz and matrix.mtx.gz files so I could use Read10X() for loading the data, but the system crashes every time.

The features and barcodes files look ok, so I think the problem lies with the matrix file. The file is so big, that it's hard for me to inspect.

Thank you,
Liesbeth

**Comment by asddf123789** [comment]
Hi Liesbeth, since our data is not generated through 10x, the file names may not conform with the read 10x function. Our [Count matrix (.mtx.gz) hosted on GEO](https://ftp.ncbi.nlm.nih.gov/geo/series/GSE199nnn/GSE199308/suppl/GSE199308%5Fgene%5Fcount.mtx.gz) can be read using Matrix::readMM( ) in R or scanpy.read_mtx( ) in Python. Please try these first. The file is around 5.3G in size, but may occupy more space after unzipped. If the issue is with memory, I can try to provide you with a smaller subset of the data.

Best,
Fanny

**Comment by OryLies** [comment]
Hi Fanny,

I tried using those functions, but both failed. Perhaps it is a memory issue. It would be very helpful if you could provide me a subset (e.g. Sox9 knockout and Wildtype) of the data to work with.

Thank you in advance!
Liesbeth

**Comment by xfanhuang** [comment]
Hi Liesbeth,

I added a few files at that might be helpful: https://atlas.gs.washington.edu/mmca_v2/public/download.html. The added matrix and meta data files correspond to the G4 WT and Sox9 KO cells.

Best,
Fanny

**Comment by asddf123789** [comment]
Hi Liesbeth,

I added a few files at that might be helpful: https://atlas.gs.washington.edu/mmca_v2/public/download.html. The added matrix and meta data files correspond to the G4 WT and Sox9 KO cells.

Best,
Fanny

**Comment by OryLies** [comment]
Thank you so much!

Best,
Liesbeth
